#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-mood
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-mood
  labels:
    type: local
spec:
  storageClassName: local-storage-mood
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-mood
spec:
  storageClassName: local-storage-mood
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

